/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'total_loans' : bigint,
  'sanctioned_count' : bigint,
  'total_sanctioned_amount' : bigint,
  'rejected_loans' : bigint,
  'stage_breakdown' : Array<[bigint, string, bigint]>,
  'disbursement_percent' : number,
  'active_loans' : bigint,
  'recent_activity' : Array<LoanStageHistory>,
  'sanctioned_percent' : number,
  'total_disbursed_amount' : bigint,
  'dropoff_rate' : number,
  'disbursed_count' : bigint,
}
export interface Document {
  'id' : bigint,
  'loan_id' : bigint,
  'file_name' : string,
  'file_url' : string,
  'file_size' : bigint,
  'uploaded_at' : Timestamp,
  'uploaded_by' : bigint,
}
export interface LoanApplication {
  'id' : bigint,
  'co_applicant_name' : string,
  'bank_name' : string,
  'updated_at' : Timestamp,
  'current_stage' : bigint,
  'is_rejected' : boolean,
  'required_amount' : bigint,
  'employment_type' : string,
  'created_at' : Timestamp,
  'user_id' : [] | [UserId],
  'loan_amount' : bigint,
  'loan_type' : string,
  'income' : bigint,
  'rejection_stage' : bigint,
  'sanction_amount' : bigint,
  'property_value' : bigint,
  'distribution_partner' : string,
  'disbursed_amount' : bigint,
  'property_type' : string,
  'is_active' : boolean,
  'rejection_reason' : string,
  'applicant_name' : string,
}
export interface LoanStageHistory {
  'id' : bigint,
  'loan_id' : bigint,
  'stage_index' : bigint,
  'show_remarks_to_user' : boolean,
  'timestamp' : Timestamp,
  'updated_by_admin_id' : bigint,
  'stage_name' : string,
  'remarks' : string,
}
export interface LoanWithHistory {
  'loan' : LoanApplication,
  'history' : Array<LoanStageHistory>,
  'assigned_user_ids' : Array<bigint>,
}
export interface PaginatedLoans {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'loans' : Array<LoanWithHistory>,
}
export interface PublicUser {
  'id' : UserId,
  'user_type' : string,
  'name' : string,
  'role' : Role,
}
export type Role = { 'admin' : null } |
  { 'user' : null };
export type Timestamp = bigint;
export type Token = string;
export interface UpdateLoanInput {
  'co_applicant_name' : [] | [string],
  'bank_name' : [] | [string],
  'required_amount' : [] | [bigint],
  'employment_type' : [] | [string],
  'loan_amount' : [] | [bigint],
  'loan_type' : [] | [string],
  'income' : [] | [bigint],
  'sanction_amount' : [] | [bigint],
  'property_value' : [] | [bigint],
  'distribution_partner' : [] | [string],
  'disbursed_amount' : [] | [bigint],
  'property_type' : [] | [string],
  'applicant_name' : [] | [string],
}
export interface UploadDocumentInput {
  'loan_id' : bigint,
  'file_name' : string,
  'file_url' : string,
  'file_size' : bigint,
}
export interface UserDashboardStats {
  'total_loans' : bigint,
  'total_sanctioned_amount' : bigint,
  'stage_breakdown' : Array<[string, bigint]>,
  'recent_loans' : Array<LoanApplication>,
  'active_loans' : bigint,
  'total_value' : bigint,
  'total_disbursed_amount' : bigint,
}
export type UserId = bigint;
export interface _SERVICE {
  'adminAddDocument' : ActorMethod<
    [string, UploadDocumentInput],
    { 'ok' : Document } |
      { 'err' : string }
  >,
  'adminAddUserToLoan' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAssignMultipleUsers' : ActorMethod<
    [string, bigint, Array<bigint>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminAssignUser' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminCreateLoan' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'adminCreateUser' : ActorMethod<
    [string, string, string, string],
    { 'ok' : PublicUser } |
      { 'err' : string }
  >,
  'adminDeleteDocument' : ActorMethod<
    [string, bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'adminDeleteLoan' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteUser' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllLoans' : ActorMethod<
    [string, bigint, bigint, string, [] | [bigint], [] | [bigint]],
    { 'ok' : PaginatedLoans } |
      { 'err' : string }
  >,
  'adminGetAllUsers' : ActorMethod<
    [string],
    { 'ok' : Array<PublicUser> } |
      { 'err' : string }
  >,
  'adminGetDashboardStats' : ActorMethod<
    [string],
    { 'ok' : DashboardStats } |
      { 'err' : string }
  >,
  'adminGetDeletedLoans' : ActorMethod<
    [string],
    { 'ok' : Array<LoanWithHistory> } |
      { 'err' : string }
  >,
  'adminGetLoanDocuments' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<Document> } |
      { 'err' : string }
  >,
  'adminGetUserById' : ActorMethod<
    [string, bigint],
    { 'ok' : [] | [PublicUser] } |
      { 'err' : string }
  >,
  'adminRejectLoan' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRemoveUserFromLoan' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRestoreLoan' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUnrejectLoan' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateAdminMobile' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminUpdateLoan' : ActorMethod<
    [string, bigint, UpdateLoanInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateStage' : ActorMethod<
    [string, bigint, bigint, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateUserType' : ActorMethod<
    [string, bigint, string],
    { 'ok' : PublicUser } |
      { 'err' : string }
  >,
  'getLoanById' : ActorMethod<
    [string, bigint],
    { 'ok' : LoanWithHistory } |
      { 'err' : string }
  >,
  'getLoanDocuments' : ActorMethod<
    [string, bigint],
    { 'ok' : Array<Document> } |
      { 'err' : string }
  >,
  'getMyLoans' : ActorMethod<
    [string],
    { 'ok' : Array<LoanWithHistory> } |
      { 'err' : string }
  >,
  'getUserDashboard' : ActorMethod<
    [string],
    { 'ok' : UserDashboardStats } |
      { 'err' : string }
  >,
  'sendOTP' : ActorMethod<[string], string>,
  'verifyOTP' : ActorMethod<
    [string, string],
    {
        'ok' : {
          'token' : Token,
          'userId' : UserId,
          'name' : string,
          'role' : string,
        }
      } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];