/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UploadDocumentInput = IDL.Record({
  'loan_id' : IDL.Nat,
  'file_name' : IDL.Text,
  'file_url' : IDL.Text,
  'file_size' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'loan_id' : IDL.Nat,
  'file_name' : IDL.Text,
  'file_url' : IDL.Text,
  'file_size' : IDL.Nat,
  'uploaded_at' : Timestamp,
  'uploaded_by' : IDL.Nat,
});
export const UserId = IDL.Nat;
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const PublicUser = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'role' : Role,
});
export const LoanApplication = IDL.Record({
  'id' : IDL.Nat,
  'co_applicant_name' : IDL.Text,
  'bank_name' : IDL.Text,
  'updated_at' : Timestamp,
  'current_stage' : IDL.Nat,
  'is_rejected' : IDL.Bool,
  'employment_type' : IDL.Text,
  'created_at' : Timestamp,
  'user_id' : IDL.Opt(UserId),
  'loan_amount' : IDL.Nat,
  'loan_type' : IDL.Text,
  'income' : IDL.Nat,
  'rejection_stage' : IDL.Nat,
  'property_value' : IDL.Nat,
  'distribution_partner' : IDL.Text,
  'property_type' : IDL.Text,
  'is_active' : IDL.Bool,
  'rejection_reason' : IDL.Text,
  'applicant_name' : IDL.Text,
});
export const LoanStageHistory = IDL.Record({
  'id' : IDL.Nat,
  'loan_id' : IDL.Nat,
  'stage_index' : IDL.Nat,
  'show_remarks_to_user' : IDL.Bool,
  'timestamp' : Timestamp,
  'updated_by_admin_id' : IDL.Nat,
  'stage_name' : IDL.Text,
  'remarks' : IDL.Text,
});
export const LoanWithHistory = IDL.Record({
  'loan' : LoanApplication,
  'history' : IDL.Vec(LoanStageHistory),
  'assigned_user_ids' : IDL.Vec(IDL.Nat),
});
export const PaginatedLoans = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'loans' : IDL.Vec(LoanWithHistory),
});
export const DashboardStats = IDL.Record({
  'total_loans' : IDL.Nat,
  'sanctioned_count' : IDL.Nat,
  'rejected_loans' : IDL.Nat,
  'stage_breakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat)),
  'disbursement_percent' : IDL.Float64,
  'active_loans' : IDL.Nat,
  'recent_activity' : IDL.Vec(LoanStageHistory),
  'sanctioned_percent' : IDL.Float64,
  'dropoff_rate' : IDL.Float64,
  'disbursed_count' : IDL.Nat,
});
export const Token = IDL.Text;

export const idlService = IDL.Service({
  'adminAddDocument' : IDL.Func(
      [IDL.Text, UploadDocumentInput],
      [IDL.Variant({ 'ok' : Document, 'err' : IDL.Text })],
      [],
    ),
  'adminAddUserToLoan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAssignMultipleUsers' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminAssignUser' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateLoan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : PublicUser, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteDocument' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteLoan' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllLoans' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Variant({ 'ok' : PaginatedLoans, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PublicUser), 'err' : IDL.Text })],
      [],
    ),
  'adminGetDashboardStats' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : DashboardStats, 'err' : IDL.Text })],
      [],
    ),
  'adminGetLoanDocuments' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(Document), 'err' : IDL.Text })],
      [],
    ),
  'adminGetUserById' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Opt(PublicUser), 'err' : IDL.Text })],
      [],
    ),
  'adminRejectLoan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRemoveUserFromLoan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUnrejectLoan' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateAdminMobile' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateLoan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateStage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getLoanById' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : LoanWithHistory, 'err' : IDL.Text })],
      [],
    ),
  'getLoanDocuments' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(Document), 'err' : IDL.Text })],
      [],
    ),
  'getMyLoans' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(LoanWithHistory), 'err' : IDL.Text })],
      [],
    ),
  'sendOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'verifyOTP' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'token' : Token,
            'userId' : UserId,
            'name' : IDL.Text,
            'role' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UploadDocumentInput = IDL.Record({
    'loan_id' : IDL.Nat,
    'file_name' : IDL.Text,
    'file_url' : IDL.Text,
    'file_size' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'loan_id' : IDL.Nat,
    'file_name' : IDL.Text,
    'file_url' : IDL.Text,
    'file_size' : IDL.Nat,
    'uploaded_at' : Timestamp,
    'uploaded_by' : IDL.Nat,
  });
  const UserId = IDL.Nat;
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const PublicUser = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'role' : Role,
  });
  const LoanApplication = IDL.Record({
    'id' : IDL.Nat,
    'co_applicant_name' : IDL.Text,
    'bank_name' : IDL.Text,
    'updated_at' : Timestamp,
    'current_stage' : IDL.Nat,
    'is_rejected' : IDL.Bool,
    'employment_type' : IDL.Text,
    'created_at' : Timestamp,
    'user_id' : IDL.Opt(UserId),
    'loan_amount' : IDL.Nat,
    'loan_type' : IDL.Text,
    'income' : IDL.Nat,
    'rejection_stage' : IDL.Nat,
    'property_value' : IDL.Nat,
    'distribution_partner' : IDL.Text,
    'property_type' : IDL.Text,
    'is_active' : IDL.Bool,
    'rejection_reason' : IDL.Text,
    'applicant_name' : IDL.Text,
  });
  const LoanStageHistory = IDL.Record({
    'id' : IDL.Nat,
    'loan_id' : IDL.Nat,
    'stage_index' : IDL.Nat,
    'show_remarks_to_user' : IDL.Bool,
    'timestamp' : Timestamp,
    'updated_by_admin_id' : IDL.Nat,
    'stage_name' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const LoanWithHistory = IDL.Record({
    'loan' : LoanApplication,
    'history' : IDL.Vec(LoanStageHistory),
    'assigned_user_ids' : IDL.Vec(IDL.Nat),
  });
  const PaginatedLoans = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'loans' : IDL.Vec(LoanWithHistory),
  });
  const DashboardStats = IDL.Record({
    'total_loans' : IDL.Nat,
    'sanctioned_count' : IDL.Nat,
    'rejected_loans' : IDL.Nat,
    'stage_breakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat)),
    'disbursement_percent' : IDL.Float64,
    'active_loans' : IDL.Nat,
    'recent_activity' : IDL.Vec(LoanStageHistory),
    'sanctioned_percent' : IDL.Float64,
    'dropoff_rate' : IDL.Float64,
    'disbursed_count' : IDL.Nat,
  });
  const Token = IDL.Text;
  
  return IDL.Service({
    'adminAddDocument' : IDL.Func(
        [IDL.Text, UploadDocumentInput],
        [IDL.Variant({ 'ok' : Document, 'err' : IDL.Text })],
        [],
      ),
    'adminAddUserToLoan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAssignMultipleUsers' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminAssignUser' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateLoan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : PublicUser, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteDocument' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteLoan' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllLoans' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Variant({ 'ok' : PaginatedLoans, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PublicUser), 'err' : IDL.Text })],
        [],
      ),
    'adminGetDashboardStats' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : DashboardStats, 'err' : IDL.Text })],
        [],
      ),
    'adminGetLoanDocuments' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(Document), 'err' : IDL.Text })],
        [],
      ),
    'adminGetUserById' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Opt(PublicUser), 'err' : IDL.Text })],
        [],
      ),
    'adminRejectLoan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRemoveUserFromLoan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUnrejectLoan' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateAdminMobile' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateLoan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateStage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getLoanById' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : LoanWithHistory, 'err' : IDL.Text })],
        [],
      ),
    'getLoanDocuments' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(Document), 'err' : IDL.Text })],
        [],
      ),
    'getMyLoans' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(LoanWithHistory), 'err' : IDL.Text })],
        [],
      ),
    'sendOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'verifyOTP' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'token' : Token,
              'userId' : UserId,
              'name' : IDL.Text,
              'role' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };