/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LoanStageHistory {
    id: bigint;
    loan_id: bigint;
    stage_index: bigint;
    show_remarks_to_user: boolean;
    timestamp: Timestamp;
    updated_by_admin_id: bigint;
    stage_name: string;
    remarks: string;
}
export type Timestamp = bigint;
export interface PaginatedLoans {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    loans: Array<LoanWithHistory>;
}
export interface Document {
    id: bigint;
    loan_id: bigint;
    file_name: string;
    file_url: string;
    file_size: bigint;
    uploaded_at: Timestamp;
    uploaded_by: bigint;
}
export interface PublicUser {
    id: UserId;
    user_type: string;
    name: string;
    role: Role;
}
export interface DashboardStats {
    total_loans: bigint;
    sanctioned_count: bigint;
    total_sanctioned_amount: bigint;
    rejected_loans: bigint;
    stage_breakdown: Array<[bigint, string, bigint]>;
    disbursement_percent: number;
    active_loans: bigint;
    recent_activity: Array<LoanStageHistory>;
    sanctioned_percent: number;
    total_disbursed_amount: bigint;
    dropoff_rate: number;
    disbursed_count: bigint;
}
export interface LoanWithHistory {
    loan: LoanApplication;
    history: Array<LoanStageHistory>;
    assigned_user_ids: Array<bigint>;
}
export interface UploadDocumentInput {
    loan_id: bigint;
    file_name: string;
    file_url: string;
    file_size: bigint;
}
export interface UpdateLoanInput {
    co_applicant_name?: string;
    bank_name?: string;
    required_amount?: bigint;
    employment_type?: string;
    loan_amount?: bigint;
    loan_type?: string;
    income?: bigint;
    sanction_amount?: bigint;
    property_value?: bigint;
    distribution_partner?: string;
    disbursed_amount?: bigint;
    property_type?: string;
    applicant_name?: string;
}
export type UserId = bigint;
export interface UserDashboardStats {
    total_loans: bigint;
    total_sanctioned_amount: bigint;
    stage_breakdown: Array<[string, bigint]>;
    recent_loans: Array<LoanApplication>;
    active_loans: bigint;
    total_value: bigint;
    total_disbursed_amount: bigint;
}
export type Token = string;
export interface LoanApplication {
    id: bigint;
    co_applicant_name: string;
    bank_name: string;
    updated_at: Timestamp;
    current_stage: bigint;
    is_rejected: boolean;
    required_amount: bigint;
    employment_type: string;
    created_at: Timestamp;
    user_id?: UserId;
    loan_amount: bigint;
    loan_type: string;
    income: bigint;
    rejection_stage: bigint;
    sanction_amount: bigint;
    property_value: bigint;
    distribution_partner: string;
    disbursed_amount: bigint;
    property_type: string;
    is_active: boolean;
    rejection_reason: string;
    applicant_name: string;
}
export enum Role {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    adminAddDocument(token: string, input: UploadDocumentInput): Promise<{
        __kind__: "ok";
        ok: Document;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminAddUserToLoan(token: string, loanId: bigint, userId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminAssignMultipleUsers(token: string, loanId: bigint, userIds: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminAssignUser(token: string, loanId: bigint, mobile: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateLoan(token: string, applicantName: string, bankName: string, loanType: string, loanAmount: bigint, mobile: string, distributionPartner: string, coApplicantName: string, employmentType: string, income: bigint, propertyType: string, propertyValue: bigint, requiredAmount: bigint | null, sanctionAmount: bigint | null, disbursedAmount: bigint | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateUser(token: string, name: string, mobile: string, role: string): Promise<{
        __kind__: "ok";
        ok: PublicUser;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteDocument(token: string, docId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteLoan(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteUser(token: string, userId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllLoans(token: string, page: bigint, pageSize: bigint, search: string, stageFilter: bigint | null, assignedUserFilter: bigint | null): Promise<{
        __kind__: "ok";
        ok: PaginatedLoans;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllUsers(token: string): Promise<{
        __kind__: "ok";
        ok: Array<PublicUser>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetDashboardStats(token: string): Promise<{
        __kind__: "ok";
        ok: DashboardStats;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetDeletedLoans(token: string): Promise<{
        __kind__: "ok";
        ok: Array<LoanWithHistory>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetLoanDocuments(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Document>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetUserById(token: string, user_id: bigint): Promise<{
        __kind__: "ok";
        ok: PublicUser | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRejectLoan(token: string, loanId: bigint, reason: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRemoveUserFromLoan(token: string, loanId: bigint, userId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRestoreLoan(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUnrejectLoan(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateAdminMobile(token: string, new_mobile: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateLoan(token: string, loanId: bigint, input: UpdateLoanInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateStage(token: string, loanId: bigint, stageIndex: bigint, remarks: string, showRemarks: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateUserType(token: string, userId: bigint, userType: string): Promise<{
        __kind__: "ok";
        ok: PublicUser;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLoanById(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: LoanWithHistory;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLoanDocuments(token: string, loanId: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Document>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyLoans(token: string): Promise<{
        __kind__: "ok";
        ok: Array<LoanWithHistory>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getUserDashboard(token: string): Promise<{
        __kind__: "ok";
        ok: UserDashboardStats;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendOTP(mobile: string): Promise<string>;
    verifyOTP(mobile: string, otp: string): Promise<{
        __kind__: "ok";
        ok: {
            token: Token;
            userId: UserId;
            name: string;
            role: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { DashboardStats as _DashboardStats, Document as _Document, LoanApplication as _LoanApplication, LoanStageHistory as _LoanStageHistory, LoanWithHistory as _LoanWithHistory, PaginatedLoans as _PaginatedLoans, PublicUser as _PublicUser, Role as _Role, Timestamp as _Timestamp, Token as _Token, UpdateLoanInput as _UpdateLoanInput, UserDashboardStats as _UserDashboardStats, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAddDocument(arg0: string, arg1: UploadDocumentInput): Promise<{
        __kind__: "ok";
        ok: Document;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddDocument(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddDocument(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAddUserToLoan(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddUserToLoan(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddUserToLoan(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAssignMultipleUsers(arg0: string, arg1: bigint, arg2: Array<bigint>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignMultipleUsers(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignMultipleUsers(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAssignUser(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignUser(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignUser(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateLoan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string, arg9: bigint, arg10: string, arg11: bigint, arg12: bigint | null, arg13: bigint | null, arg14: bigint | null): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateLoan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg14));
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateLoan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg14));
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: PublicUser;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateUser(arg0, arg1, arg2, arg3);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateUser(arg0, arg1, arg2, arg3);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteDocument(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteDocument(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteDocument(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteLoan(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteLoan(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteLoan(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteUser(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllLoans(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: bigint | null, arg5: bigint | null): Promise<{
        __kind__: "ok";
        ok: PaginatedLoans;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllLoans(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllLoans(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<PublicUser>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDashboardStats(arg0: string): Promise<{
        __kind__: "ok";
        ok: DashboardStats;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetDeletedLoans(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<LoanWithHistory>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDeletedLoans(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDeletedLoans(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetLoanDocuments(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Document>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetLoanDocuments(arg0, arg1);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetLoanDocuments(arg0, arg1);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserById(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: PublicUser | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserById(arg0, arg1);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserById(arg0, arg1);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectLoan(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectLoan(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectLoan(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveUserFromLoan(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveUserFromLoan(arg0, arg1, arg2);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveUserFromLoan(arg0, arg1, arg2);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRestoreLoan(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRestoreLoan(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRestoreLoan(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUnrejectLoan(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnrejectLoan(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnrejectLoan(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateAdminMobile(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateAdminMobile(arg0, arg1);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateAdminMobile(arg0, arg1);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateLoan(arg0: string, arg1: bigint, arg2: UpdateLoanInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateLoan(arg0, arg1, to_candid_UpdateLoanInput_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateLoan(arg0, arg1, to_candid_UpdateLoanInput_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateStage(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateUserType(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: PublicUser;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateUserType(arg0, arg1, arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateUserType(arg0, arg1, arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanById(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: LoanWithHistory;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanById(arg0, arg1);
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanById(arg0, arg1);
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanDocuments(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Array<Document>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanDocuments(arg0, arg1);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanDocuments(arg0, arg1);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLoans(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<LoanWithHistory>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoans(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoans(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDashboard(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserDashboardStats;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDashboard(arg0);
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDashboard(arg0);
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendOTP(arg0);
            return result;
        }
    }
    async verifyOTP(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            token: Token;
            userId: UserId;
            name: string;
            role: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0, arg1);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0, arg1);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_LoanApplication_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LoanWithHistory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanWithHistory): LoanWithHistory {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedLoans_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedLoans): PaginatedLoans {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PublicUser_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUser): PublicUser {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserDashboardStats_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDashboardStats): UserDashboardStats {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUser]): PublicUser | null {
    return value.length === 0 ? null : from_candid_PublicUser_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    loans: Array<_LoanWithHistory>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    loans: Array<LoanWithHistory>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        loans: from_candid_vec_n14(_uploadFile, _downloadFile, value.loans)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loan: _LoanApplication;
    history: Array<_LoanStageHistory>;
    assigned_user_ids: Array<bigint>;
}): {
    loan: LoanApplication;
    history: Array<LoanStageHistory>;
    assigned_user_ids: Array<bigint>;
} {
    return {
        loan: from_candid_LoanApplication_n17(_uploadFile, _downloadFile, value.loan),
        history: value.history,
        assigned_user_ids: value.assigned_user_ids
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    co_applicant_name: string;
    bank_name: string;
    updated_at: _Timestamp;
    current_stage: bigint;
    is_rejected: boolean;
    required_amount: bigint;
    employment_type: string;
    created_at: _Timestamp;
    user_id: [] | [_UserId];
    loan_amount: bigint;
    loan_type: string;
    income: bigint;
    rejection_stage: bigint;
    sanction_amount: bigint;
    property_value: bigint;
    distribution_partner: string;
    disbursed_amount: bigint;
    property_type: string;
    is_active: boolean;
    rejection_reason: string;
    applicant_name: string;
}): {
    id: bigint;
    co_applicant_name: string;
    bank_name: string;
    updated_at: Timestamp;
    current_stage: bigint;
    is_rejected: boolean;
    required_amount: bigint;
    employment_type: string;
    created_at: Timestamp;
    user_id?: UserId;
    loan_amount: bigint;
    loan_type: string;
    income: bigint;
    rejection_stage: bigint;
    sanction_amount: bigint;
    property_value: bigint;
    distribution_partner: string;
    disbursed_amount: bigint;
    property_type: string;
    is_active: boolean;
    rejection_reason: string;
    applicant_name: string;
} {
    return {
        id: value.id,
        co_applicant_name: value.co_applicant_name,
        bank_name: value.bank_name,
        updated_at: value.updated_at,
        current_stage: value.current_stage,
        is_rejected: value.is_rejected,
        required_amount: value.required_amount,
        employment_type: value.employment_type,
        created_at: value.created_at,
        user_id: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.user_id)),
        loan_amount: value.loan_amount,
        loan_type: value.loan_type,
        income: value.income,
        rejection_stage: value.rejection_stage,
        sanction_amount: value.sanction_amount,
        property_value: value.property_value,
        distribution_partner: value.distribution_partner,
        disbursed_amount: value.disbursed_amount,
        property_type: value.property_type,
        is_active: value.is_active,
        rejection_reason: value.rejection_reason,
        applicant_name: value.applicant_name
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total_loans: bigint;
    total_sanctioned_amount: bigint;
    stage_breakdown: Array<[string, bigint]>;
    recent_loans: Array<_LoanApplication>;
    active_loans: bigint;
    total_value: bigint;
    total_disbursed_amount: bigint;
}): {
    total_loans: bigint;
    total_sanctioned_amount: bigint;
    stage_breakdown: Array<[string, bigint]>;
    recent_loans: Array<LoanApplication>;
    active_loans: bigint;
    total_value: bigint;
    total_disbursed_amount: bigint;
} {
    return {
        total_loans: value.total_loans,
        total_sanctioned_amount: value.total_sanctioned_amount,
        stage_breakdown: value.stage_breakdown,
        recent_loans: from_candid_vec_n34(_uploadFile, _downloadFile, value.recent_loans),
        active_loans: value.active_loans,
        total_value: value.total_value,
        total_disbursed_amount: value.total_disbursed_amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    user_type: string;
    name: string;
    role: _Role;
}): {
    id: UserId;
    user_type: string;
    name: string;
    role: Role;
} {
    return {
        id: value.id,
        user_type: value.user_type,
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Document;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Document;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PaginatedLoans;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PaginatedLoans;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PaginatedLoans_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_PublicUser>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<PublicUser>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DashboardStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DashboardStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_LoanWithHistory>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<LoanWithHistory>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Document>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Document>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_PublicUser];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PublicUser | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LoanWithHistory;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LoanWithHistory;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LoanWithHistory_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserDashboardStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserDashboardStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserDashboardStats_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: _Token;
        userId: _UserId;
        name: string;
        role: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: Token;
        userId: UserId;
        name: string;
        role: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PublicUser;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PublicUser;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PublicUser_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanWithHistory>): Array<LoanWithHistory> {
    return value.map((x)=>from_candid_LoanWithHistory_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicUser>): Array<PublicUser> {
    return value.map((x)=>from_candid_PublicUser_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplication>): Array<LoanApplication> {
    return value.map((x)=>from_candid_LoanApplication_n17(_uploadFile, _downloadFile, x));
}
function to_candid_UpdateLoanInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLoanInput): _UpdateLoanInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    co_applicant_name?: string;
    bank_name?: string;
    required_amount?: bigint;
    employment_type?: string;
    loan_amount?: bigint;
    loan_type?: string;
    income?: bigint;
    sanction_amount?: bigint;
    property_value?: bigint;
    distribution_partner?: string;
    disbursed_amount?: bigint;
    property_type?: string;
    applicant_name?: string;
}): {
    co_applicant_name: [] | [string];
    bank_name: [] | [string];
    required_amount: [] | [bigint];
    employment_type: [] | [string];
    loan_amount: [] | [bigint];
    loan_type: [] | [string];
    income: [] | [bigint];
    sanction_amount: [] | [bigint];
    property_value: [] | [bigint];
    distribution_partner: [] | [string];
    disbursed_amount: [] | [bigint];
    property_type: [] | [string];
    applicant_name: [] | [string];
} {
    return {
        co_applicant_name: value.co_applicant_name ? candid_some(value.co_applicant_name) : candid_none(),
        bank_name: value.bank_name ? candid_some(value.bank_name) : candid_none(),
        required_amount: value.required_amount ? candid_some(value.required_amount) : candid_none(),
        employment_type: value.employment_type ? candid_some(value.employment_type) : candid_none(),
        loan_amount: value.loan_amount ? candid_some(value.loan_amount) : candid_none(),
        loan_type: value.loan_type ? candid_some(value.loan_type) : candid_none(),
        income: value.income ? candid_some(value.income) : candid_none(),
        sanction_amount: value.sanction_amount ? candid_some(value.sanction_amount) : candid_none(),
        property_value: value.property_value ? candid_some(value.property_value) : candid_none(),
        distribution_partner: value.distribution_partner ? candid_some(value.distribution_partner) : candid_none(),
        disbursed_amount: value.disbursed_amount ? candid_some(value.disbursed_amount) : candid_none(),
        property_type: value.property_type ? candid_some(value.property_type) : candid_none(),
        applicant_name: value.applicant_name ? candid_some(value.applicant_name) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
